### ISSUE TITLE
Can't use Glass Pane to make item frames invisible

### ISSUE THREAD

**Issue by SplendidAlakey** [CraftyCorvid/ImprovedSigns#29]
**MC** 1.19.2
**QL** 0.18.3
**Improved Signs** 1.2.0

Changing the `"invisibleFrameItem"` option to `"GLASS_PANE"` in `improved-signs.json5` doesn't do anything, the actual item is still amethyst shard and the glass pane does not turn the frames invisible. There are no errors in logs, so I'm not including any.

**Comment by CraftyCorvid** [comment]
Fixed on latest version
