### ISSUE TITLE
retainDyeOnSignCopy=false still copy color and glow

### ISSUE THREAD

**Issue by MeeniMc** [CraftyCorvid/ImprovedSigns#41]
The option retainDyeOnSignCopy set to false has no effect (the copied signs still have color and glow texts).

**Comment by MeeniMc** [comment]
Not sure if this is the reason you are holding on publishing the 1.20.4 version, but that bug is also present in the prior release, so no new harm is done by just putting out the new release.

**Comment by CraftyCorvid** [comment]
I’m on vacation so won’t be able to publish until January.

**Comment by CraftyCorvid** [comment]
Fixed and pushed a new release
