### ISSUE TITLE
"invisibleFrameItem": "GLASS_PANE" doesn't work 

### ISSUE THREAD

**Issue by alinka62679** [craftycorvid/ImprovedSigns#42]
Hi, changing the parameter "invisibleFrameItem": **"GLASS_PANE"** in the configuration does not work for me

MC 1.20.1

https://github.com/CraftyCorvid/ImprovedSigns/assets/72551624/45556908-a003-4bc5-8c5e-d24c1e95687c

**Comment by craftycorvid** [comment]
This bug was fixed in new versions of the mod
